name: first CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  welcome_script:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome part
        run: echo "Hello, guys ðŸ˜…"
      - name: Get info
        run: |
          echo "Getting comp info...."
          whoami
          sleep 5
          pwd

  welcome_script_in_parallel:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome part
        run: echo "Hello, guys ðŸ˜…"
      - name: Get info
        run: |
          echo "Getting comp info...."
          whoami
          sleep 10
          pwd

  checking:
    needs: [welcome_script, welcome_script_in_parallel]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.11, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Install python ${{ matrix.python-version }}
        uses: actions/checkout@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest black isort faker
      - name: check with linter
        run: |
          black . --check
          isort .
          flake8 .
          pytest .
      - name: print secret
        run: echo "${{ secrets.SECRET_KEY }}"