name: first CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  welcome_script:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome part
        run: echo 'Hello, guys ğŸŒ·'
      - name: Get info
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is"
          whoami
          sleep 10
          pwd
  welcome_script_in_parallel:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome part
        run: echo 'Hello, guys ğŸŒ·'
      - name: Get info
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is"
          whoami
          sleep 10
  build:
    needs: [welcome_script]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.11, 3.11.3]
    steps:
      - uses: actions/checkout@v3
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: check with linter
        run: |
          flake8 .
          black . --check
      - name: pytest
        run: |
          pytest .
      - name: final
        run: echo "good!!!!!!!!!!!!"